on: workflow_dispatch
name: Deploy App
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy App to AKS
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks get-credentials --name ${{ secrets.CLUSTER_NAME }} --resource-group ${{ secrets.AZURE_RG }}
          az aks install-cli
          # kubectl delete ns guid --force
          kubectl create ns guid
          kubectl create deployment pod-guid --image=ibmcom/curl:4.2.0-build.2 -n guid -- /bin/sh '-c' 'while true; do curl https://<your-azurefunction-service>.azurewebsites.net/api/<your-azurefunction>?event=DEMO-$RANDOM; sleep 1; done'
