name: Push image to GAR

on: workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: us-centra1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
          
      - name: Build and push to GAR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/api:latest  
          
          #tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/api:${{ github.sha }}  
          
