# This is a basic workflow to help you get started with Actions

name: Push image to GitHub Registry

on: workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
           
      - name: Build and Push Image to GitHub Registry
        uses: docker/build-push-action@v2
        #working-directory: /src
        with:
          #context: .
          #file: ./Dockerfile
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ secrets.your_repository }}/api:latest
            
          #ghcr.io/${{ secrets.your_repository }}/api:${{ github.sha }}
          
          #labels: ${{ steps.meta.outputs.labels }}

