on: workflow_dispatch
name: ARM-Template Deploying AKS
jobs:
  arm-template-deploy-aks:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./lab-aks/azure-deploy.json
        # parameters: storageAccounts_name=oamx
        parameters: ./lab-aks/parameters.json

      # output containerName variable from template
 #  - run: echo ${{ steps.deploy.outputs.containerName }}
