apiVersion: v1
kind: Namespace
metadata:
  name: serverless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: call-function
  name: call-function
  namespace: serverless
spec:
  replicas: 2
  selector:
    matchLabels:
      app: call-function
  strategy: {}
  template:
    metadata:
      labels:
        app: call-function
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - while true; do curl https://<your-azurefunction-service>.azurewebsites.net/api/<your-azurefunction>?event=DEMO-$RANDOM; sleep 1; done
        image: ibmcom/curl:4.2.0-build.2
        name: call-function
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
          limits:
            memory: "15Mi"
            cpu: "125m"
