on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acraksworkshop.azurecr.io
        username: ${{ secrets.acr_acraksworkshop_username }}
        password: ${{ secrets.acr_acraksworkshop_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acraksworkshop.azurecr.io/aksclusterdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ${{ secrets.your_acr_name }}.azurecr.io/${{ secrets.your_acr_repo }}:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksclusterdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akscluster-demo8f13 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akscluster-demo8f13`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akscluster-demo8f13
        container-registry-url: ${{ secrets.your_acr_name }}.azurecr.io
        container-registry-username: ${{ secrets.acr_acraksworkshop_username }}
        container-registry-password: ${{ secrets.acr_acraksworkshop_password }}
        secret-name: aksclusterdedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akscluster-demo8f13
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{ secrets.your_acr_name }}.azurecr.io/${{ secrets.your_acr_repo }}:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdedockerauth
