on: workflow_dispatch
name: Delete AKS Cluster
jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Delete AKS Cluster with AZ CLI
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az account set --subscription {{ secrets.AZURE_SUBS }}
   #       az aks delete --name AKSCluster-Demo --resource-group IaC_Workshop --yes
