on: workflow_dispatch
name: Delete AKS Cluster
jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        azcliversion: 2.16.0
        inlineScript: |
          az aks delete --name AKSCluster-Demo --resource-group IaC_Workshop
