# This is a basic workflow to help you get started with Actions

name: Push image to Docker Hub

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
           
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          #context: .
          #file: ./Dockerfile
          #platforms: linux/amd64
          push: true
          tags: <your-dockethub-account>/api:${{ github.sha }}
          
        
